name: Keep Portfolio Awake

on:
  schedule:
    # Runs every 15 minutes (cron syntax)
    - cron: '*/15 * * * *'
  workflow_dispatch:  # Allows manual trigger from GitHub UI

jobs:
  ping-portfolio:
    name: Ping Render Portfolio
    runs-on: ubuntu-latest
    
    steps:
      - name: Check current time
        run: echo "🕒 Pinging portfolio at $(date)"
      
      - name: Send wake-up request
        run: |
          echo "📡 Sending request to portfolio..."
          
          # Replace with your actual Render URL
          curl -X GET "https://new-portfolio-h88c.onrender.com" \
            -H "User-Agent: GitHub-Actions-Keep-Alive" \
            --max-time 30 \
            --connect-timeout 10 \
            --retry 3 \
            --retry-delay 5 \
            --silent \
            --output /dev/null \
            --write-out "✅ Status: %{http_code}\n⏱️  Time: %{time_total}s\n"
      
      - name: Log completion
        run: echo "✅ Ping completed at $(date)"